### ISSUE TITLE
RosettaConsole 'Search Card' doesn't work

### ISSUE THREAD

**Issue by JinDDeok** [utilForever/RosettaStone#449]
```
Command > -n "Chaos Strike"
========================================
             Search Result!             
========================================
There are no cards matching your search condition.
Command > -n Chaos Strike 
Error in command line: Unrecognized token: Strike
Command > -n "Chaos"
========================================
             Search Result!             
========================================
There are no cards matching your search condition.
Command > -n Chaos
========================================
             Search Result!             
========================================
There are no cards matching your search condition.
```
I tried various methods, but the search result didn't come out.

My environment is ubuntu 20.04, gcc 9.3.0, cmake 3.16.3

**Comment by beuoon** [comment]
This problem is occurred because the default value of 'GameTag' enum class is not 'INVALID'.
First of all, 'mechanic' exists in a search option. It needs 'GameTag' enum class value.

Currently, 'GameTag' enum class in 'CardEnums.hpp' is as follows.
```
enum class GameTag
{
#define X(a) a,
#include "GameTagCustom.def"
#include "Rosetta/Common/Enums/GameTag.def"
#undef X
};
```

Although 'INVALID' value exist in "Rosetta/Common/Enums/GameTag.def", this file is included after "GameTagCustom.def" is included.
So first value of 'GameTag' enum class is not 'INVALID'. (Now, the first value is 'HEADCRACK_COMBO' that first value of 'GameTagCustom.def').
And default value of enum class is first value. (refer to 'StrToEnum' function in 'CardEnums.hpp'.)

'ProcessSearchCommand' method in 'Console.cpp' is as follows:
```
bool mechanicsCondition = (filter.gameTag == GameTag::INVALID || card->HasGameTag(filter.gameTag));
```
According to code, 'mechanic' option must be 'INVALID' or card's game tag to search card.
But 'mechanic' option value is 'HEADCRACK_COMBO' when you no set 'mechanic' option.
Therefore, nothing was searched.

This problem can be fixed by changing order of that include file as same as following.
```
enum class GameTag
{
#define X(a) a,
#include "Rosetta/Common/Enums/GameTag.def"
#include "GameTagCustom.def"
#undef X
};
```

**Comment by utilForever** [comment]
Thank you for the report! I think @JinDDek or @beuoon should fix it. Who would like to work on it?
